sharmaaditya570191/BossY

README.md

Added database files name and usage of `faker.js`.

Updated docs for database

---

src/components/AllIdeas.js
src/components/Idea.js
src/components/Minion.js
src/components/SingleWorkRow.js
src/components/SingleWorkRowDescription.js

Fix errors in the console

---

.github/ISSUE_TEMPLATE/bug_report.md

- Fixes #35 
- Added Bug reporting template

Added Bug reporting template

---

.gitignore
models/minions.js

Task completed #71 
@sharmaaditya570191 kindly review

Created Schema for Minion using Mongoose

---

server/models/Meeting.js

Created schema for meeting

---

README.md

Fixes #59 
Added contact us section in readme which will redirect to the slack channel

Contact us added

---

server/models/Work.js

fixes: #72 
@sharmaaditya570191 @somyaranjan26 please review the PR.

created schema of Work using mongoose

---

src/components/Idea.js

fixes #26 
@sharmaaditya570191 Please review my PR and suggest any changes if needed.

changed Idea component to function component

---

src/components/Work.js

fixes #29 Issue
Changed class component to functional component using Hooks.

Change class to functional component work

---

package-lock.json
package.json

I have solved the bug as the site is not working due to some error in the dependencies and Babel file.
@sharmaaditya570191 Kindly check it :)

Bug solved in the site

---

README.md
models/minions.js
package-lock.json
package.json
server.js
server/api.js
server/checkMillionDollarIdea.js
server/db.js
server/models/Idea.js
server/models/Meeting.js
server/models/Work.js
src/components/AllIdeas.js
src/components/AllMinions.js
src/components/Heading.js
src/components/Home.js
src/components/Idea.js
src/components/IdeaListItem.js
src/components/Minion.js
src/index.js
src/store/minions.js

Fixes #118 
@sharmaaditya570191 , kindly review

Added Es-6 imports and exports to the project

---

.github/access.yml

Check if the invoker has access.

added access control action

---

.github/workflows/esLint.yml

aaded esLint Plugin action

---

.github/workflows/actionForge.yml

Puppet Forge modules are great at making your life easier.These modules meet our standards for being well-written, reliable, and actively maintained. Modules can contain tasks that take action outside of a desired state managed by Puppet.
This action allows you to upload your module to Puppet Forge.
As puppet forge is popularly used and it will be very usefull for the project.

added action forge action

---

.github/workflows/rebase_a_PR.yml

When you rebase, Git finds the base of your branch,finds all the commits between that base and HEAD and re-plays those commits on the HEAD of the branch you're rebasing onto. Git actually creates new commits that represent what your changes look like on top of master.
Simply comment /rebase to trigger the action.

added automatically rebasing a PR

---

.github/workflows/greetings.yml

added greeting github action.
Related to #113.

added greeting github action

---

src/assets/css/style.css
src/components/Heading.js

added button to change mode between day and night mode

---

src/assets/css/style.css

Fixes #60 
**Description
Changed the color theme of the website.
**Attaching the screenshot below:

Changed the Color theme to lighter color

---

package.json

Fixes #XX
**Checklist:**
index.md`).

Error in package.json

---

README.md

Fixes #XX
**Checklist:**
index.md`).

Added bossy workspace in readme.md

---

src/middleware/renderView.jsx
src/shared/cache.es6

Fixes #XX
**Checklist:**
index.md`).

added necessary caches

---

package.json

Fixes #XX
**Checklist:**
index.md`).

added compression

---

src/shared/cookies.es6

Fixes #XX
**Checklist:**
index.md`).

added the isomorphic model of  cookie

---

src/components/Footer.js
src/components/Idea.js
src/components/Work.js

Fixes #XX
**Checklist:**
index.md`).

error resolved
